import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Benefit from '@/components/Benefit'
import Bmi from '@/components/Bmi'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Nav from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
    <section id='whatis'>
      <Header/>
    </section>
    <section id='benefit'>
      <Benefit/>
    </section>
    <section id='calculator'>
      <Bmi/>
    </section>
    <section id='aboutus'>
      <Footer/>
    </section>
    </>
  )
}
